# Generated by Django 4.2 on 2023-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
